### ISSUE TITLE
Include ps in container for nextflow?

### ISSUE THREAD

**Issue by photocyte** [Dfam-consortium/TETools#12]
Hi there, just a quick note that it would be nice to have `ps` within the TE Tools Docker container, as that allows for better compatability with Nextflow. See here:
https://github.com/nextflow-io/nextflow/issues/1289#issuecomment-738783841

**Comment by jebrosen** [comment]
Does this entirely prevent the container from running from within nextflow, or only the tracing and metrics functionality?

The full list of programs that need be installed inside containers run via nextflow in order for metrics to work is at https://www.nextflow.io/docs/latest/tracing.html#tasks:

> `awk`, `date`, `grep`, `egrep`, `ps`, `sed`, `tail`, `tee`

Most of these (except `ps`) are probably already included; I should be able to add the missing ones some time next week.

**Comment by photocyte** [comment]
I'm able to run the container (via [this workflow](https://github.com/photocyte/repeatModeler2_nf)) without `ps`, by just turning off the `trace` and `report` nextflow functionality, but would be nice to have :)

**Comment by jebrosen** [comment]
This has been added to the `Dockerfile`, and it will be included in the next update to the container (planned for this week!)
