### ISSUE TITLE
RepeatClassifier does not recognize the LIBDIR variable shown in the README

### ISSUE THREAD

**Issue by qisun2** [Dfam-consortium/TETools#13]
I followed instructions on https://github.com/Dfam-consortium/TETools#readme to add Repbase.  After I set LIBDIR to the new Libraries directory, can RepeatModeler/RepeatClassifier pick up the LIBDIR value and use Repbase?  I read the code, it seems that RepeatClassifier still uses the old /opt/RepeatMasker/Libraries/RepeatMasker.lib file.

**Comment by jebrosen** [comment]
You are right, `RepeatClassifier` does not respect LIBDIR. I will think a bit about how to best solve this in RepeatModeler and/or in the instructions in the README.

Here is one alternative method that should work; something like this could be incorporated into the README instead of the current instructions.

Instead of copying only the `Libraries/` subdirectory, copy the entire `RepeatMasker/` directory. Install RepBase RepeatMasker Edition in this new copy with `addRepBase.pl`. Finally, set this path in `REPEATMASKER_DIR` when running RepeatModeler instead of using `LIBDIR`.

**Comment by r-mashoodh** [comment]
I think my issue is related, as I can't get RepeatModeler to accept the new Dir ...

I followed the instructions for creating the new Dfam+Repbase libraries, seems to have worked, I have a separate RepeatMasker directory

`export REPEATMASKER_DIR=RepeatMasker/
singularity exec docker://dfam/tetools:latest RepeatModeler -database genome -engine ncbi -threads 56 -LTRStruct > velutina_run_recovery.out`

The log looks like this, which suggests its not properly accessing the Libraries ...

`Refinement: 00:00:01 (hh:mm:ss) Elapsed Time
  WARNING: Refiner did not return a consensus for /rds/project/rds-sHE3M4BjkMM/EarlGrey/velutina/RM_242972.SatMar40940152023/round-1/family-38.fa.
  WARNING: Refiner did not return a consensus for /rds/project/rds-sHE3M4BjkMM/EarlGrey/velutina/RM_242972.SatMar40940152023/round-1/family-1.fa.`

`Instance Gathering: 00:00:01 (hh:mm:ss) Elapsed Time
About to run 18 refinement jobs
Refinement: 00:00:00 (hh:mm:ss) Elapsed Time
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
  WARNING: Refiner did not return a consensus.
Family Refinement: 00:00:01 (hh:mm:ss) Elapsed Time
Round Time: 00:38:41 (hh:mm:ss) Elapsed Time : 0 families discovered.`

do you have any advice?

thanks so much.

**Comment by asgray** [comment]
Hi, sorry for the long delay. I was able to run RepeatModeler successfully with the latest version of the container, but please let me know if this is still an issue.
One thing to confirm is that your data is being mounted to the container correctly. Singularity mounts `$PWD` by default, but some system admins have this feature disabled. A simple check is to enter the container with `singularity shell <container name>` and the run `ls -al`. If the mount is enabled by default you should see the contents of the host directory. If the mount isn't enabled, you can do it by hand with the `-B $PWD` argument.
