### ISSUE TITLE
famdef and eleredef steps fail when using the docker image on a Mac

### ISSUE THREAD

**Issue by mickey-spongebob** [Dfam-consortium/TETools#14]
Hi :-) 

Hope this finds you well! Thank you so much for the tool.

I successfully downloaded the docker image onto my Mac as per the instructions on the README page. I also manage to execute the BuildDatabase command fine, however when I try to execute the RepeatModeler command (-database <name_of_database -pa 10 -LTRStruct ), the code fails. So far it has failed twice and I'm re-running it again in case it solves itself :-)

The first time the error stated: "famdef failed. Exit code 1024"
The second time, after re-running with the -recover_Dir option: "eleredef failed. Exit code 11"

The log files appear intact, and the only clue that something is wrong comes from the Exit code details.

Have you encountered this issue with a Mac? Or is it simply a matter of trying it a couple more times to see if it runs to completion? I should say that both times it failed after round_3, so I could still use the files in this folder or from the earlier rounds, but I just wanted to see if I can run it to completion.

Any advice would be greatly appreciated! 

Cheers,
kevin

**Comment by mickey-spongebob** [comment]
Update:

I am now able to make it to round4 of the RepeatModeler phase, but I still receive an exit code of 1024 as it's running RECON (famdef)

**Comment by mickey-spongebob** [comment]
Update:

I successfully installed the same docker image on an Ubuntu virtual machine and it seems to be running well so far (currently on round5). Seems to be a problem unique to Mac maybe??

**Comment by jebrosen** [comment]
> The second time, after re-running with the -recover_Dir option: "eleredef failed. Exit code 11"

This sounds like a similar problem to this one: <https://github.com/Dfam-consortium/RepeatModeler/issues/140#issuecomment-861032472>. If you can share with us the seed numbers and source genomes, and/or `round-` directories from some of the failed RECON runs, that may help us to troubleshoot the problem.

> Have you encountered this issue with a Mac? Or is it simply a matter of trying it a couple more times to see if it runs to completion?

This one should (hopefully) not be a Mac or Docker-specific problem, since Docker for Mac runs a full Linux virtual machine. I think this one is more likely to be an environment issue (e.g. low on free memory), and/or bad luck with the chosen seed number and genome samples.

**Comment by mickey-spongebob** [comment]
Hi :-)

Thank you for the reply and apologies for the delayed response. As we speak, the Ubuntu version is running smoothly despite having the same settings. The only thing I can think of, is that the parallelisation may have failed for the Mac installation. I unfortunately deleted the files you are asking for as I attempted several rounds of re-running and finally settled on using a VM to set up an Ubuntu machine to run the program. I could try to re-run the Mac version once my analysis on the ubuntu machine finishes (currently at the LTR discovery step with no issues since it started running).

Cheers

**Comment by jebrosen** [comment]
I took another look at these errors:

> famdef failed. Exit code 1024

I found code in `famdef.c` that would cause this particular error, and it appears to be a bug in RECON. Re-runs would not be expected to reproduce the error unless the same seed number was used.

> The second time, after re-running with the -recover_Dir option: "eleredef failed. Exit code 11"

This one is also likely to be a bug in RECON, although (less likely) it can occur in out-of-memory and similar situations.


If you do reproduce the problem, please file the issue to [RepeatModeler](https://github.com/Dfam-consortium/RepeatModeler), including the genome and seed number and/or the contents of the `round-` dir that failed.
