### ISSUE TITLE
accessing util scripts within singularity container?

### ISSUE THREAD

**Issue by r-mashoodh** [Dfam-consortium/TETools#15]
Sorry for the silly question -- Is there a way to access the utilities scripts available in RepeatMasker within the singularity container? eg. `calcDivergenceFromAlign.pl` etc

**Comment by jebrosen** [comment]
The `/util/` directories are included on the PATH inside the container already, so you should be able to run them simply by their name like an installed command. They can also be found in `/opt/RepeatMasker/util/` and `/opt/RepeatModeler/util/`.

**Comment by r-mashoodh** [comment]
ah thanks! 

it is possible that the new RepeatMasker doesn't have the `queryRepeatDatabase.pl `script anymore?

**Comment by jebrosen** [comment]
Yes, `queryRepeatDatabase.pl` has been replaced. The same functionality is now available via the `famdb.py` command, and repeatmasker.help has been updated to use it in its examples instead.
