### ISSUE TITLE
ERRO[10728] error waiting for container: unexpected EOF

### ISSUE THREAD

**Issue by ld9866** [Dfam-consortium/TETools#18]
## l print the "RepeatModeler -pa 10 -database Test -LTRStruct >& 1.run.out"
##The log showed "Comparison Time: 00:07:52 (hh:mm:ss) Elapsed Time, 1368539 HSPs Collected
  - RECON: Running imagespread..
RECON Elapsed: 00:00:02 (hh:mm:ss) Elapsed Time
  - RECON: Running initial definition of elements ( eledef )..
RECON Elapsed: 00:00:14 (hh:mm:ss) Elapsed Time
  - RECON: Running re-definition of elements ( eleredef ).."

ERRO[10728] error waiting for container: unexpected EOF

  l do not know how to slove it, can you help me?
Thank you!

**Comment by jebrosen** [comment]
> ERRO[10728] error waiting for container: unexpected EOF

I believe that (very confusing!) error message is from Docker. I found one possible cause that seems likely: running out of memory. The eleredef step can be very memory-intensive on some genomes and has caused similar problems for many users in various environments.

Does this problem occur for you frequently, or only with specific input files?

**Comment by ld9866** [comment]
Thank you very much for your reply. As you said, it depends on our storage. We have 1t running memory, but this single task will occupy about 700g. Now I use CONDA for installation, and then modify ninja. Now this part can run normally. I haven't tried to use docker. I will use it later for testing.
Thank you very much for your reply!
Good luck
