### ISSUE TITLE
BuildDatabase step problem

### ISSUE THREAD

**Issue by Niohuruzh** [Dfam-consortium/TETools#21]
Hello, TEtools team

**Describe the bug**
BuildDatabase command dont work well this time. 

**To Reproduce**
`BuildDatabase -name JEC21 /data/JEC21/db/JEC21.fasta`

**Expected behavior**
`BuildDatabase: Cannot open file JEC21.translation`
I'm confused because I can run this last time. I just use a new *.fasta file. And im sure that the file is same with the one as before.

**Host system (please complete as much of the following information as you can find out):**
 - `uname -a`
 - Linux bbc0927150e3 5.10.47-linuxkit # 1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 GNU/Linux
 - `lsb_release -a`
 - No LSB modules are available
 - Distributor ID: Denian
 -  Description: Debian GNU/Linux 9.13(stretch) 
 - Release:9.13 Codename:stretch
 - `docker --version`
 - 20.10.10.build b485636

Looking for your reply
Best Regards!

**Comment by jebrosen** [comment]
Hi @Niohuruzh, `BuildDatabase` outputs the `Cannot open file *.translation` message when it cannot write to the file.

By default, `BuildDatabase` writes files to the current directory. If the current directory in the container is incorrect, you may need to change to a writable directory first with `cd`. You can also pass a full path to BuildDatabase, such as `-name /data/JEC21/db/JEC21`. I hope one of these options resolves the problem!

**Comment by Niohuruzh** [comment]
Hi jebrosen,
That works well when I `cd /data/JEC21/db` and run `BuildDatabase ***`
Thanks very much!

Best Regards!

**Comment by jebrosen** [comment]
Excellent! If you have further questions, please do re-open this or a new issue.
