### ISSUE TITLE
Error in Job submitting of Slurm on cluster : if it is possible to disable the need for an internet connection 

### ISSUE THREAD

**Issue by Hai1983** [Dfam-consortium/TETools#22]
Dear Authors of program.

Thanks for very nice program.
Now I run RepeatModeler with Dfam TE Tools Container. ( with using Singularity Container)
Job can work directly on command line. But When I summit it as job, it failed.

My Job:
(
_#!/bin/bash
#SBATCH --time=1:00:00 # hh:mm:ss
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4000 # megabytes
singularity run -B  /scratch/ulg/bbasv/daomhai/Docker docker://dfam/tetools:latest RepeatModeler -database Catfish22 -engine ncbi -pa 32 )_

The result in Slurm:
(
_time="2021-12-26T19:39:42+01:00" level=warning msg="\"/run/user/3003415\" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/3003415: no such file or directory: Trying to pull image in the event that it is a public image."
FATAL:   Unable to handle docker://dfam/tetools:latest uri: failed to get checksum for docker://dfam/tetools:latest: error pinging docker registry registry-1.docker.io: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:47463->[::1]:53: read: connection refused._ )

I contact with manager of Cluster he said that compute nodes does not have a direct internet access**.
So I would like to ask the authors of the program if it is possible to disable the need for an internet connection when running 
 job program on cluster ??
Or do you have other advices ??

Thank you for your help and I look forward to hearing your advice.

Thanks in advance 
Sincerely yours
Hai

**Comment by jebrosen** [comment]
Hi,

I think I saw in another issue that you have found a solution to this problem already. In case not, or if someone else has the same question:

`singularity run` can be used with a docker URL, or with a container image file. If you have internet access on another computer, you can first download the image to a file with e.g. `singularity build tetools_1.4.sif docker://dfam/tetools:1.4` and then transfer `tetools_1.4.sif` to a location that is accessible to the compute nodes.

**Comment by Hai1983** [comment]
Dear Dr Jebrosen.

Thanks for your reply.
I try to solve it by  create a Singularity image on the login node with the following command:
$ singularity pull docker://dfam/tetools:latest
This will create a singularity image named "tetools_latest.sif" that I can then use this for your job running on the compute node.
I hope this way is ok for my work ?!!.
But I face with other issue : https://github.com/Dfam-consortium/RepeatModeler/issues/160
With ( eleredef failed. Exit code 768 with Singularity).

Please give me some advice on this issue 

Thank you for your help and I look forward to hearing your advice.

Thanks in advance and Happy new year!!!
Sincerely yours
Hai

**Comment by jebrosen** [comment]
Ah, I had not seen about `singularity pull`. For this purpose, both `singularity build` and `singularity pull` should do the same as each other. And, currently "latest" is the same as "1.4". That looks good to me!


And, I will reply on your other question soon.

Best regards,
Jeb

**Comment by Hai1983** [comment]
Dear Jeb .

Thanks for your kind reply.

Sincerely,
Hai

**Comment by jebrosen** [comment]
You are very welcome! I will close this issue; please feel free to comment or open a new issue if you have further questions or problems.
