### ISSUE TITLE
RepeatMasker returning impossible coordinates

### ISSUE THREAD

**Issue by jamesdgalbraith** [Dfam-consortium/TETools#23]
**Describe the bug**

Many repeat coordinates hits in the ".out" file are longer than the query repeat.
For example, the line below is data is from the ".out", which a hit is to a consensus repeat (DR0021180) which is 3217bp long, yet says it's a hit to 4804-5218:

`15803   11.6  1.8  1.5  ctg_1      35113158  35113313 (105938908) + DR0021180          LINE/RTE-BovB            4804   5218   (195)   43774`

However the likely corresponding line from the ".align" file do not have this issue:
`15803 7.67 1.17 0.28 ctg_1 35110690 35112821 (105939400) DR0021180#LINE/RTE-BovB 1 2151 (1066) m_b606s001i18 43774`

Of note there is are hits from other BovBs which overlap the coordinates(from .align):

`1366 29.30 3.74 8.29 ctg_1 35112325 35113180 (105939041) BovB_Ml#LINE/RTE-BovB 456 1275 (174) m_b606s001i19 43774
2098 17.41 0.51 1.81 ctg_1 35112819 35113210 (105939011) DR0087524#LINE/RTE-BovB 1444 1830 (438) m_b606s001i21 43774
520 31.22 9.94 4.46 ctg_1 35112938 35113299 (105938922) DR0143386#LINE/RTE-BovB 4838 5218 (195) m_b606s001i22 43774
714 17.39 5.07 0.00 ctg_1 35113176 35113313 (105938908) DR0020736#LINE/RTE-BovB 2466 2610 (1) m_b606s001i23 43774`

The library used was from 

https://www.dfam.org/releases/Dfam_3.5/families/Dfam.h5.gz

**To Reproduce**
Steps to reproduce the behavior, including the full command line used to start the container and any commands run inside the container.

RepeatMasker -species reptilia -pa 32 genome.fasta

**Expected behavior**

The repeats coordinates should not be outside that of the reference sequence.

**Host system (please complete as much of the following information as you can find out):**
Linux 5.4.0-94-generic #106-Ubuntu
The above data is from an manual install from the RepeatMasker website, but I have had the same issue on multiple other reptile genomes using RepeatMasker installed from the docker container

**Additional context**
This is on a species of snake. I have an assumption this may be due to a growing level of redundancy with the reptile Dfam sequences, along with misclassified sequences.

**Comment by rmhubley** [comment]
Hi There.  Please report this to the RepeatMasker github site (https://github.com/rmhubley/RepeatMasker/issues)  as this pertains to RepeatMasker in-general.  But a quick response, this is an issue with the way ProcessRepeats adjudicates conflicting hits.  In cases of significant overlap between compatible families (close-subfamilies, same class/subclass etc), ProcessRepeats will assume that the consensus is not complete and allow joining of the annotation into a single annotation.  This does, unfortunately break the direct mapping of the final *.out consensus ranges in some cases.  In many cases this system works well, however as you may find there will be cases (e.g a tandem duplication of a family, or a poorly curated TE library) where it doesn't go so well.  As you found, the *.align file contains the original alignments that contributed to the final *.out annotation call and should have correct coordinates back to the consensus sequences.
