### ISSUE TITLE
forksys:  Program terminated by a signal 9.

### ISSUE THREAD

**Issue by 3719left** [Dfam-consortium/TETools#26]
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
forksys:  Program terminated by a signal 9.
The executing command was:  /opt/RepeatMasker/ProcessRepeats -lib RM_919634.MonOct101112052022/consensi.fa.classified -orifile GCA_018340775.1_ASM1834077v1_genomic.fna -maskSource /PBIO2/Taxus/communicationbiology/RM_3932828.ThuOct131112242022/GCA_018340775.1_ASM1834077v1_genomic.fna /PBIO2/Taxus/communicationbiology/RM_3932828.ThuOct131112242022/GCA_018340775.1_ASM1834077v1_genomic.fna.cat.gz
Singularity> ls                                                                 CommunicationBioQC.tar.gz  Cplant.03.nni
CommunicationBioQCtest     Cplant.03.nog
Cplant-families.fa         Cplant.03.nsq
Cplant-families.stk        Cplant.nal
Cplant-rmod.log            Cplant.translation
Cplant.00.nhr              Crun.out
Cplant.00.nin              GCA_018340775.1_ASM1834077v1_genomic.fna
Cplant.00.nnd              RM_919634.MonOct101112052022
Cplant.00.nni              SRR14089425
Cplant.00.nog              SRR14089426
Cplant.00.nsq              SRR14089427
Cplant.01.nhr              SRR14089428
Cplant.01.nin              SRR14089429
Cplant.01.nnd              SRR14089430
Cplant.01.nni              SRR14089431
Cplant.01.nog              SRR14089432
Cplant.01.nsq              SRR14089433
Cplant.02.nhr              SRR14089434
Cplant.02.nin              SRR14089435
Cplant.02.nnd              SRR14089436
Cplant.02.nni              SRR14453978
Cplant.02.nog              SRR14453979
Cplant.02.nsq              SRR14865989
Cplant.03.nhr              commfastq
Cplant.03.nin              repeatmaskout
Cplant.03.nnd
Singularity> RepeatMasker -nolow -no_is -norna -pa 16 -lib RM_919634.MonOct101112052022/consensi.fa.classified -dir repeatmaskout GCA_018340775.1_ASM1834077v1_genomic.fna 

Above is what I got after running for a long time. I thinks something is broken. Can you help me figure it out? Thanks.

**Comment by asgray** [comment]
Hi sorry for the delay. 
A process being terminated by a signal 9 means that it was killed by the operating system, usually because it ran out of available memory. How large are your input files? It's likely that the best solution is to fragment them into separate files and run them individually.
