### ISSUE TITLE
TRF path error while running a Docker

### ISSUE THREAD

**Issue by majie5976** [Dfam-consortium/TETools#3]
Dear, 
       i was trying to install Repeatmodeler2 via docker container. but i am facing a TRF PATH error problem. i am attaching a screenshot of that, please help me to solve this issue.

![TRF ERROR](https://user-images.githubusercontent.com/54849045/75760020-7a22a580-5d71-11ea-8924-dcdf085cf91c.png)

**Comment by jebrosen** [comment]
You can specify a path to TRF manually if it's not in your `PATH`. I expect that this should work for you:

`./dfam-tetools.sh --trf-path=./TRF.linux64`

**Comment by jageis-fldm** [comment]
Ran into a similar problem. I did specify the TRF path but still getting the same error even though it is executable
![image](https://user-images.githubusercontent.com/61885160/76111200-b255fe00-5f94-11ea-9ec1-2c27f7184b8a.png)

**Comment by jebrosen** [comment]
I made a mistake earlier when I referred to `--trf-path=`. It is `--trf_prgm=`.

---

@jageis-fldm I think the issue there is that `getopt` is very different on macOS, so I will need to work around that somehow. In the meantime, you can run it manually. This command would start the container the same way that `dfam-tetools.sh` would have; note that you do need to use the Linux version of TRF:

`docker run -it --rm --mount type=bind,source="$(pwd)",target=/work --mount type=bind,source="./trf409.linux64",target=/opt/trf,ro --user "$(id -u):$(id -g)" --workdir "/work" --env "HOME=/work" "dfam/tetools:1"`

However, I am not sure if it will work as expected on Mac and I do not have Docker for Mac set up to test it with.

**Comment by jageis-fldm** [comment]
Thanks for the prompt response! Appears to be working now...

**Comment by jebrosen** [comment]
I have updated `dfam-tetools.sh` in commit ac133a2 to only use commands that are available on macOS, so I believe the script should work now although I have still not tested the actual container.

You can re-run `curl -sSLO https://github.com/Dfam-consortium/TETools/raw/master/dfam-tetools.sh` to get the latest version.
