### ISSUE TITLE
rmblast does not work in new docker image for TETools 1.86. 

### ISSUE THREAD

**Issue by qisun2** [Dfam-consortium/TETools#32]
In the latest version of docker image (dfam/tetools:latest 1.86), running rmblastn gives this error message: 
/opt/rmblast/bin/rmblastn: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/rmblast/bin/rmblastn)

**Comment by OliverPStuart** [comment]
I'm also having this issue.

**Comment by asgray** [comment]
Hi all, sorry for the inconvenience. The new release (1.87) addresses this issue. Rmblast should work properly now
