### ISSUE TITLE
error of repeatmasker in container

### ISSUE THREAD

**Issue by sqwwww** [Dfam-consortium/TETools#33]
I used the container with RepeatModeler Version 2.0.5 and RepeatMasker version 4.1.5. The RepeatModeler was successfully completed, while RepeatMasker reported an error. here is my error message, what can I do to make it work?

Standard Output:
RepeatMasker version 4.1.5
Search Engine: NCBI/RMBLAST [ 2.14.1+ ]

Standard Error:
Taxonomy::new() needs a path for a famdb file!
 at /opt/RepeatMasker/RepeatMasker line 658.

**Comment by asgray** [comment]
Hi, sorry for the delay. Is this still an issue with the latest version of the container? If so, can you provide the command you were running?
