### ISSUE TITLE
Docker Image Cannot Run LTRStruct pipeline

### ISSUE THREAD

**Issue by suz11001** [Dfam-consortium/TETools#34]
Hello,

I am having trouble running the LTRstruct pipeline with the (latest) docker image, I received the following error:
`Dependency checking: Error: The RMblast engine is not installed in RepeatMasker!`

This is how I am executing repeatmodeler:
`shifter  --module=none --image=dfam/tetools@sha256:e1e1a6f1cd8badf25746865ca8978760f86ab13ec37684ff0fd81b5b8f37ca2c BuildDatabase -engine ncbi -name arabi Athaliana_167.fa`

`shifter  --module=none --image=dfam/tetools@sha256:e1e1a6f1cd8badf25746865ca8978760f86ab13ec37684ff0fd81b5b8f37ca2c RepeatModeler -database arabi -threads 120 -engine ncbi -LTRStruct  &> repeatmodeler.log`

I am using the nersc computing system (x86_64) and [shifter](https://docs.nersc.gov/development/shifter/) to pull the docker image. When I run the image, I know rmblast is there and it is in the path. So I am unsure as to why the dependency check is failing. Additionally, I dug in to the LRET logs and the makeblastdb.log has the following error: `BLAST Database creation error: mdb_env_open: Function not implemented`

 Any guidance is much appreciated!

**Comment by asgray** [comment]
Hi Sumaira, unfortunately I wasn't able to reproduce your error. Are you able to share a more complete error log? You're right that RMBlast should be included in the image, and RepeatModeler is configured to use it during the creation of the image.

One possible issue is that RepeatModeler assumes that your database will be available in `/opt/src`. This means that you should include something similar to `-v $(pwd):/opt/src` as an argument for both commands. I believe the shifter equivalent would look like `--volume=<local directory>:/opt/src`, but I've only worked with docker directly.
