### ISSUE TITLE
Customizing RepeatMasker libraries: Absent

### ISSUE THREAD

**Issue by jsg8145** [Dfam-consortium/TETools#35]
Hello,
thank you for tools, and I had some errors when I tried to customize my own repeat masker libraries.
Now, I use this tools from singularity:
`singularity pull dfam-tetools-latest.sif docker://dfam/tetools:latest`

Then, I used this command to use singularity container.
`singularity run dfam-tetools-latest.sif`

Next, I copied the `opt/ReaPeatMasker/Libraries` to `/home/$USER` and download dfam38_full.8.h5.gz in the folder after exit.
`cp -r Libraries /home/$USER`
`exit`
`cd /home/$USER/Libraries/famdb`
`wget https://www.dfam.org/releases/Dfam_3.8/families/FamDB/dfam38_full.8.h5.gz && gunzip dfam38_full.8.h5.gz`
`chown -R $USER ./Libraries`

And I mounted my home directory to /work inside the container:
`cd /home/$USER`
`singularity run -B $(pwd):/work dfam-tetools-latest.sif`

Finally, I tried to regenerate my own libraries:
`cd /opt/RepeatMasker`
`./tetoolsDfamUpdate.pl`
but I had a log like this. It seems the tools cannot find Partition 8.

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.utf-8",
	LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

Checking for libraries...

 - Found a FamDB root partition

Building RMBlast frozen libraries..
The program is installed with a the following repeat libraries:

FamDB Directory     : /opt/RepeatMasker/Libraries/famdb
FamDB Generator     : famdb.py v1.0
FamDB Format Version: 1.0
FamDB Creation Date : 2023-11-15 11:30:15.311827

Database: Dfam
Version : 3.8
Date    : 2023-11-14

Dfam - A database of transposable element (TE) sequence alignments and HMMs.

1 Partitions Present
Total consensus sequences present: 295552
Total HMMs present               : 295552

Partition Details
-----------------
 Partition 0 [dfam38_full.0.h5]: root - Mammalia, Amoebozoa, Bacteria <bacteria>, Choanoflagellata, Rhodophyta, Haptista, Metamonada, Fungi, Sar, Placozoa, Ctenophora <comb jellies>, Filasterea, Spiralia, Discoba, Cnidaria, Porifera, Viruses
     Consensi: 295552, HMMs: 295552

 Partition 1 [ Absent ]: Obtectomera 

 Partition 2 [ Absent ]: Euteleosteomorpha 

 Partition 3 [ Absent ]: Sarcopterygii - Sauropsida, Coelacanthimorpha, Amphibia, Dipnomorpha

 Partition 4 [ Absent ]: Diptera 

 Partition 5 [ Absent ]: Viridiplantae 

 Partition 6 [ Absent ]: Deuterostomia - Chondrichthyes, Hemichordata, Cladistia, Holostei, Tunicata, Cephalochordata, Cyclostomata <vertebrates>, Osteoglossocephala, Otomorpha, Elopocephalai, Echinodermata, Chondrostei

 Partition 7 [ Absent ]: Hymenoptera 

 Partition 8 [ Absent ]: Ecdysozoa - Nematoda, Gelechioidea, Yponomeutoidea, Incurvarioidea, Chelicerata, Collembola, Polyneoptera, Tineoidea, Apoditrysia, Monocondylia, Strepsiptera, Palaeoptera, Neuropterida, Crustacea, Coleoptera, Siphonaptera, Trichoptera, Paraneoptera, Myriapoda, Scalidophora

Further documentation on the program may be found here:
  /opt/RepeatMasker/repeatmasker.help

Is there anything wrong with the progress of the task? How can I fix it?

**Comment by asgray** [comment]
Hi, instead of 
`singularity run -B $(pwd):/work dfam-tetools-latest.sif`, 
try running 
`singularity run -B /home/$USER/Libraries:/opt/RepeatMasker/Libraries dfam-tetools-latest.sif`

If the steps to copy the library data out of the container worked, and you've added any additional files to the host system library directory, you just need to bind it in where RepeatMasker knows to look for it and run the update script. The `/work` directory in the container is just used for copying the data out, and any time you want the container to use your local library, just bind it in as above. 
Also bear in mind that you may need to delete `rmlib.config` for `tetoolsDfamUpdate.pl` to work.

Let me know if that works!

**Comment by jsg8145** [comment]
Hi,
Now it works! Thank you for your advice.
I think not deleting the `rmlib.config` file might also have been the cause.
