### ISSUE TITLE
famdb.py: command not found

### ISSUE THREAD

**Issue by jsg8145** [Dfam-consortium/TETools#40]
Hello,
thank you for tools, and I had an error when I tried using famdb.py in singularity container
Now, I use a singularity container which released at Dec 12, 2023 and I use it well until Jan 30, 2024.
However, it didn't work well when I tried using that again today.
Here is my command line and error.

`singularity run dfam-tetools-latest.sif `
Singularity> `famdb.py names -h`
bash: famdb.py: command not found

I updated h5py also using `pip3 install --upgrade h5py`

How can I use famdb.py again in this singularity container? Should I download the latest version of it released 3 weeks ago?

**Comment by asgray** [comment]
Hi, the command works for me:
```
~/projects/TETools$ singularity run ./tetools
Apptainer> famdb.py names -h
usage: famdb.py names [-h] [-f <format>] term [term ...]

List the names and taxonomy identifiers of a clade.

positional arguments:
  term                  search term. Can be an NCBI taxonomy identifier or part of a scientific or common name

options:
  -h, --help            show this help message and exit
  -f <format>, --format <format>
                        choose output format. The default is 'pretty'. 'json' is more appropriate for scripts.
```
The latest version of the container (1.88.5) doesn't have any changes to RepeatMasker or FamDB, so you shouldn't need to update, and the container should have a working version of `h5py` bundled with it.
The only reason `famdb.py` should have stopped working that I can think of is that something is changing/has changed your path variable. 

`famdb.py` should be on the container `PATH` by default, but try invoking it directly with `/opt/RepeatMasker/famdb.py`. Also try running `echo $PATH` from inside the container. You should see `:/opt/RepeatMasker:` somewhere in the path string. If it's not there, it's possible that some admin setting for Singularity is disrupting it.

**Comment by jsg8145** [comment]
Hi,
It works with command `/opt/RepeatMasker/famdb.py`
Thanks for your comment!

I couldn't find out the reason why it didn't work when I used command just `famdb.py`.
Maybe admin setting for singularity is the problem.
