### ISSUE TITLE
LTRPipeline : Error - could not open clusters.dat!

### ISSUE THREAD

**Issue by yasutoishii** [Dfam-consortium/TETools#42]
Hello,

Thank you for maintaining the useful tools.
I encountered an error when I ran RepeatModeler to generate species-specific library for masking a de novo assembly.

**Describe the bug**
The error was
```
Clustering...LTRPipeline: Error - could not cluster MAFFT results.
             : 00:00:00 (hh:mm:ss) Elapsed Time
LTRPipeline : Error - could not open /work/RM_13.SatJun290653562024/LTR_1007365.SunJun300251312024/clusters.dat! at /opt/RepeatModeler/LTRPipeline line 333.
```

**To Reproduce**
The command was:
```
SCAFFOLD_FASTA=out_JBAT.FINAL.fa    ### My assembly file
PREFIX=scaffold
BuildDatabase -name ${PREFIX} ${SCAFFOLD_FASTA}
RepeatModeler -database ${PREFIX} -LTRStruct -threads 40
```
I mounted my local dir on /work with following command:
```
sudo docker run -it --rm -v $(pwd):/work dfam/tetools:latest
```

**Host system (please complete as much of the following information as you can find out):**
- My OS is: Ubuntu 20.04.6 LTS
- Docker info: Docker version 24.0.2, build cb74dfc
- Docker image: latest one created 4 months ago
- Computing environment setup: single computer

**Additional context**
As the error said, I can't fine `clusters.dat` in /work/RM_13.SatJun290653562024/LTR_1007365.SunJun300251312024.
The directory includes four files:
```
LtrRetriever-redundant-results.fa
LtrRetriever-redundant-results.fa.no_orient
mafft-alignment.fa
raw-struct-results.txt
```

Best,
Yasuto

**Comment by kim2039** [comment]
This error is most likely caused by the NINJA version upgrade.
If downloading from the URL of the latest release of NINJA and compiling it, it shows that it is actually downloading a 0.95 version, not 0.99.
This has also been posted in an Issue of NINJA.
https://github.com/TravisWheelerLab/NINJA/issues/46
I suggest using the older version of Ninja until this issue is resolved.

**Comment by yasutoishii** [comment]
Thanks Kim,

The version of NINJA was 0.95, as you mentioned.
I tried tetools v. 1.8, but LTRpipeline provided another error:
```
Running LtrHarvest...LtrPipeline: GenomeTools failed to run ltrharvest. Error code: 139
LtrPipeline: Ltrharvest returned an unexpected result line:
Segmentation fault (core dumped)
LTRPipeline: No results returned from LTR structural finder ( LtrHarvest ).
```

I assume the cause is the shotage of RAM (my PC has ~ 200 GB RAM).
I'll try it with more RAM!

**Comment by rmhubley** [comment]
Ugh...sorry about this mixup here.  The most recent version of Ninja (0.99-cluster_only) was not built correctly and was missing the command-line options for clustering -- this would definitely cause the LTR pipeline to fail out.  I have just generated a new Ninja release (1.00-cluster_only available here: https://github.com/TravisWheelerLab/NINJA/releases ), that does have the clustering functionality, reports the correct version with "-v", *and* supports both x86 and arm64.  This should be compatible with the current released version of RepeatModeler.

**Comment by yasutoishii** [comment]
Hi Hubley,

Thank you for your concern.
For the current genome, I ended up running RepeatModeler without the `-lrtstruct` option, as the segmentation fault error could not be resolved.
I will try the `-lrtstruct` option on another genome. Thanks again!

**Comment by xiaozhuo-wang** [comment]
Hello,
Thank you for maintaining the useful tools.
I had the same problem. I used Ninja-0.97-cluster_only (although I used the download address of 0.98). Later I changed to Ninja-1.00-cluster_only and reconfigured it, but there was still the same error. I don't know where I was wrong at the moment, I hope I can get your help. Thanks
`LTR Structural Analysis
=======================
Running LtrHarvest...     : 32:35:02 (hh:mm:ss) Elapsed Time
Running Ltr_retriever...  : 00:34:11 (hh:mm:ss) Elapsed Time
Aligning instances...     : 00:02:20 (hh:mm:ss) Elapsed Time
Clustering...LTRPipeline: Error - could not cluster MAFFT results.
             : 00:00:00 (hh:mm:ss) Elapsed Time
LTRPipeline : Error - could not open /data01/wangzizhuo/Gb4_denovo/03.assembly_hifiasm/hifi5/14.annotion/11.repeatAnno/RM_35103.MonMay51655282025/LTR_69567.TueMay61041452025/clusters.dat! at /data01/wangzizhuo/software/RepeatModeler-2.0.6/LTRPipeline line 333.
  -- No LTRs identified through structural analysis
LTRPipeline Time: 33:11:44 (hh:mm:ss) Elapsed Time`

` Ninja -v
Version 0.97-cluster_only`
