### ISSUE TITLE
RepeatModeler BuildDatabase can not open file

### ISSUE THREAD

**Issue by hidvegin** [Dfam-consortium/TETools#43]
**Describe the bug**
`BuildDatabase` can not open file.translation from fasta files in directory.

**To Reproduce**
I tried this script on a HPC in singularity container:

```
module load singularity
singularity exec --no-home --env TEMP=/temp/ --workdir /data/ \
 --bind /temps/:/temp/ \
 --bind /repeatmodeler/results/:/data/ \
 --bind /input/fasta/:/files/ \
 /singularity_files/dfam-tetools-latest.sif BuildDatabase -name file -engine ncbi -dir /files/
```

I got this error:

`BuildDatabase: Cannot open file file.translation`

The fasta files contain a de novo assembly with 8.5 million sequences.

**Expected behavior**
I expected thet BuildDatabase will generate the database from fasta files in directory.

**Host system (please complete as much of the following information as you can find out):**

```
 LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterprise
Description:	Red Hat Enterprise Linux release 8.6 (Ootpa)
Release:	8.6
Codename:	Ootpa
```
Singularity-CE 4.0.1

**Comment by asgray** [comment]
Sorry for the wait, but if this is still an issue, removing the `--no-home` flag clears this error for me. RepeatModeler tries to put it's output in the directory where it was invoked, so it might be worth trying a `(cd /target_path; singularity exec ...)` type command.
