### ISSUE TITLE
Add TRF

### ISSUE THREAD

**Issue by nathanweeks** [Dfam-consortium/TETools#5]
TRF is now open source: https://github.com/Benson-Genomics-Lab/TRF

It would be convenient if it were included in the TE Tools container image.

**Comment by jebrosen** [comment]
This was done a while ago, but I was waiting for RepeatMasker 4.1.1 before a new release and then forgot to push everything up at the end. Thanks for this reminder!


The latest version of `dfam-tetools.sh` no longer asks for a path to TRF on the host, and the `1`, `1.2`, `latest` tags have been updated on Docker Hub and include TRF.
