### ISSUE TITLE
How to make and use a RepeatMasker custom library inside the singularity container?

### ISSUE THREAD

**Issue by xyz0o** [Dfam-consortium/TETools#7]
Hi,

I have installed the Rmodeler2 singularity container and I have merged the RepBase library to the RMasker library which is integrated inside the container using below instruction:

```
# Navigate to an appropriate directory that is persistent outside the container
$ cd /work

# Make a copy of RepeatMasker's Libraries directory here
$ cp -r /opt/RepeatMasker/Libraries/ ./

# Extract RepBase (the .tar.gz file unpacks files into Libraries/)
$ tar -x -f /work/path/to/RepBaseRepeatMaskerEdition-#######.tar.gz

# Run the 'addRepBase.pl' script (part of the RepeatMasker package) to merge the databases,
# specifying the custom Libraries directory.
$ addRepBase.pl -libdir Libraries/

# Run RepeatMasker with the LIBDIR environment variable set
$ export LIBDIR=/path/to/Libraries
```
I have run the Repeatmodeler on a non-model organism's genome assembly:
singularity exec --bind $PWD:$PWD ./tetools.sif RepeatModeler -database monCan3F9 -pa 40 -LTRStruct

now before running the RepeatMasker, I want to merge the monCan3F9-families.fa with the "Dfam.h5" library, how should I do that?

Also, regarding your new RM version, should I utilize the "queryRepeatDatabase" option to separately drag Drosophila library or not? because I saw it in older versions of RM but couldn't find in your current documentation with the container.

this is how inside my Library looks like now.
![capture4](https://user-images.githubusercontent.com/77616805/106574347-7a0fc480-6543-11eb-9d4f-5600eb9f804a.jpg)

**Comment by jebrosen** [comment]
Closing this issue, since this was answered elsewhere:

> > now before running the RepeatMasker, I want to merge the monCan3F9-families.fa with the "Dfam.h5" library, how should I do that?
> > Also, regarding your new RM version, should I utilize the "queryRepeatDatabase" option to separately drag Drosophila library or not? because I saw it in older versions of RM but couldn't find in your current documentation with the container.
> 
> For a general approach, see the first part of this answer: [Dfam-consortium/RepeatModeler#40 (comment)](https://github.com/Dfam-consortium/RepeatModeler/issues/40#issuecomment-527565134)
> 
> In particular, it sounds like you are asking about this:
> 
> > (...) we recommend that the the output of RepeatModeler combined with already defined repeats ( RepeatMasker/util/queryRepeatDatabase -species ... ) be placed into a custom library and then run through RepeatMasker with the "-lib" option.
> 
> `queryRepeatDatabase` was replaced with `famdb.py`. To extract a species-specific FASTA library from the installed libraries, you can run this command while inside your `Libraries` directory:
> `famdb.py -i RepeatMaskerLib.h5 families --format fasta_name --include-class-in-name --ancestors --descendants 'species name' >species-rm.fa`
> 
> Then, the files can be combined with `cat`: `cat species-rm.fa monCan3F9-families.fa > monCan3F9-combined.fa`. The resulting `monCan3F9-combined.fa` file can be used with RepeatMasker's `-lib` option.

The full conversation can be found at: <https://github.com/Dfam-consortium/RepeatModeler/issues/117#issuecomment-771804307>.
